### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by lhr081124** [tiredvekster/LiteAntiCheat#1]
I found two problems when using it: 1. It incorrectly checks enchantment effects in the ecoEnchants plugin and 2. LAC does not check when the player uses the meteor client, setting the speed mode to strafe and controlling the timer value to within 3. But overall this anti-cheat performance is very strong, hope to update as soon as possible, thank you!

**Comment by lhr081124** [comment]
Because I'm a Chinese, I'm having a hard time using Discord to send you a message, please forgive me!

**Comment by tiredvekster** [comment]
Hi! Sorry for being late.
1. This is a paid plugin so I don't know how fix this. It'd be better if you ask the EcoEnchants developer
2. I'll try to fix this. I guess, MorePacketsB check is far too low-sensitive
3. Thanks
